
//@ts-nocheck
import { PatientWithoutScansAndNotes } from '../../../../types/PatientTypes';

export const patients: PatientWithoutScansAndNotes[] = [
	{
		id: '1',
		sequenceNumber: 1,
		firstName: 'Michael',
		lastName: 'Davis',
		email: 'michael.davis@example.com',
		address: {
			line1: '123 High Street',
			line2: 'Apt 2B',
			line3: '',
			county: 'London',
			city: 'London',
			postcode: 'SW1A 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1990-05-15').toISOString(),
		lastSeenDate: new Date('2021-08-20').toISOString(),
		gender: 'Female',
		height: 165,
		weight: 60,
		bmi: 22,
		phoneNumber: 7123456789,
		status: 'New Patient',
		treatmentStartDate: new Date('2021-03-10').toISOString(),
		nextVisitDate: new Date('2021-09-10').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE2',
			previousAmputation: false,
			yearsDiagnosedWithDiabetes: 5,
			previousFootTreatmentOrDysfunction: 'None',
			otherDiabeticAssociatedComplications: 'None',
			lastHbA1cReading: 7.2,
			lastHbA1cDate: new Date('2021-08-15').toISOString(),
			lastLipidProfile: 150,
			lastLipidProfileDate: new Date('2021-08-15').toISOString(),
			latestBp: 120,
			latestBpDate: new Date('2021-08-20').toISOString(),
			medications: true,
			medicationsInfo: 'Metformin',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '2',
		sequenceNumber: 2,
		firstName: 'Alice',
		lastName: 'Smith',
		email: 'alice.smith@example.com',
		address: {
			line1: '456 Elm Street',
			line2: 'Apt 3C',
			line3: '',
			county: 'Manchester',
			city: 'Manchester',
			postcode: 'M1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1985-10-20').toISOString(),
		lastSeenDate: new Date('2021-08-25').toISOString(),
		gender: 'Male',
		height: 175,
		weight: 70,
		bmi: 23,
		phoneNumber: 7234567890,
		status: 'Scans reviewed',
		treatmentStartDate: new Date('2021-04-15').toISOString(),
		nextVisitDate: new Date('2021-09-15').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE1',
			previousAmputation: true,
			yearsDiagnosedWithDiabetes: 10,
			previousFootTreatmentOrDysfunction: 'Orthopedic shoes',
			otherDiabeticAssociatedComplications: 'Retinopathy',
			lastHbA1cReading: 8.5,
			lastHbA1cDate: new Date('2021-08-20').toISOString(),
			lastLipidProfile: 160,
			lastLipidProfileDate: new Date('2021-08-20').toISOString(),
			latestBp: 130,
			latestBpDate: new Date('2021-08-25').toISOString(),
			medications: true,
			medicationsInfo: 'Insulin',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '3',
		sequenceNumber: 3,
		firstName: 'Emily',
		lastName: 'Johnson',
		email: 'emily.johnson@example.com',
		address: {
			line1: '789 Oak Avenue',
			line2: 'Apt 4D',
			line3: '',
			county: 'Birmingham',
			city: 'Birmingham',
			postcode: 'B1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1978-03-12').toISOString(),
		lastSeenDate: new Date('2021-08-30').toISOString(),
		gender: 'Female',
		height: 160,
		weight: 65,
		bmi: 25,
		phoneNumber: 7345678901,
		status: 'New Patient',
		treatmentStartDate: new Date('2021-05-20').toISOString(),
		nextVisitDate: new Date('2021-09-20').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE2',
			previousAmputation: false,
			yearsDiagnosedWithDiabetes: 8,
			previousFootTreatmentOrDysfunction: 'None',
			otherDiabeticAssociatedComplications: 'Neuropathy',
			lastHbA1cReading: 7.8,
			lastHbA1cDate: new Date('2021-08-25').toISOString(),
			lastLipidProfile: 170,
			lastLipidProfileDate: new Date('2021-08-25').toISOString(),
			latestBp: 125,
			latestBpDate: new Date('2021-08-30').toISOString(),
			medications: true,
			medicationsInfo: 'Metformin, Statins',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '4',
		sequenceNumber: 4,
		firstName: 'David',
		lastName: 'Brown',
		email: 'david.brown@example.com',
		address: {
			line1: '101 Pine Road',
			line2: 'Apt 5E',
			line3: '',
			county: 'Glasgow',
			city: 'Glasgow',
			postcode: 'G1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1982-08-05').toISOString(),
		lastSeenDate: new Date('2021-09-05').toISOString(),
		gender: 'Male',
		height: 180,
		weight: 80,
		bmi: 24,
		phoneNumber: 7456789012,
		status: 'Scans reviewed',
		treatmentStartDate: new Date('2021-06-25').toISOString(),
		nextVisitDate: new Date('2021-09-25').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE1',
			previousAmputation: true,
			yearsDiagnosedWithDiabetes: 15,
			previousFootTreatmentOrDysfunction: 'Amputation',
			otherDiabeticAssociatedComplications: 'Nephropathy',
			lastHbA1cReading: 9.2,
			lastHbA1cDate: new Date('2021-08-30').toISOString(),
			lastLipidProfile: 180,
			lastLipidProfileDate: new Date('2021-08-30').toISOString(),
			latestBp: 140,
			latestBpDate: new Date('2021-09-05').toISOString(),
			medications: true,
			medicationsInfo: 'Insulin, ACE inhibitors',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '5',
		sequenceNumber: 5,
		firstName: 'Sophia',
		lastName: 'Wilson',
		email: 'sophia.wilson@example.com',
		address: {
			line1: '222 Maple Lane',
			line2: 'Apt 6F',
			line3: '',
			county: 'Liverpool',
			city: 'Liverpool',
			postcode: 'L1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1995-12-18').toISOString(),
		lastSeenDate: new Date('2021-09-10').toISOString(),
		gender: 'Female',
		height: 170,
		weight: 55,
		bmi: 19,
		phoneNumber: 7567890123,
		status: 'Scans reviewed',
		treatmentStartDate: new Date('2021-07-05').toISOString(),
		nextVisitDate: new Date('2021-10-05').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE2',
			previousAmputation: false,
			yearsDiagnosedWithDiabetes: 3,
			previousFootTreatmentOrDysfunction: 'None',
			otherDiabeticAssociatedComplications: 'None',
			lastHbA1cReading: 6.5,
			lastHbA1cDate: new Date('2021-09-05').toISOString(),
			lastLipidProfile: 140,
			lastLipidProfileDate: new Date('2021-09-05').toISOString(),
			latestBp: 110,
			latestBpDate: new Date('2021-09-10').toISOString(),
			medications: true,
			medicationsInfo: 'Metformin',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '6',
		sequenceNumber: 6,
		firstName: 'Oliver',
		lastName: 'Martinez',
		email: 'oliver.martinez@example.com',
		address: {
			line1: '333 Cedar Street',
			line2: 'Apt 7G',
			line3: '',
			county: 'Edinburgh',
			city: 'Edinburgh',
			postcode: 'EH1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1980-07-25').toISOString(),
		lastSeenDate: new Date('2021-09-15').toISOString(),
		gender: 'Male',
		height: 175,
		weight: 75,
		bmi: 24,
		phoneNumber: 7678901234,
		status: 'Scans not reviewed',
		treatmentStartDate: new Date('2021-08-10').toISOString(),
		nextVisitDate: new Date('2021-10-10').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE1',
			previousAmputation: true,
			yearsDiagnosedWithDiabetes: 12,
			previousFootTreatmentOrDysfunction: 'Orthopedic shoes',
			otherDiabeticAssociatedComplications: 'Neuropathy',
			lastHbA1cReading: 8.0,
			lastHbA1cDate: new Date('2021-09-10').toISOString(),
			lastLipidProfile: 155,
			lastLipidProfileDate: new Date('2021-09-10').toISOString(),
			latestBp: 125,
			latestBpDate: new Date('2021-09-15').toISOString(),
			medications: true,
			medicationsInfo: 'Insulin',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '7',
		sequenceNumber: 7,
		firstName: 'Lily',
		lastName: 'Garcia',
		email: 'lily.garcia@example.com',
		address: {
			line1: '444 Birch Road',
			line2: 'Apt 8H',
			line3: '',
			county: 'Cardiff',
			city: 'Cardiff',
			postcode: 'CF1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1972-04-30').toISOString(),
		lastSeenDate: new Date('2021-09-20').toISOString(),
		gender: 'Female',
		height: 160,
		weight: 70,
		bmi: 27,
		phoneNumber: 7789012345,
		status: 'Missing scans',
		treatmentStartDate: new Date('2021-09-05').toISOString(),
		nextVisitDate: new Date('2021-10-05').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE2',
			previousAmputation: false,
			yearsDiagnosedWithDiabetes: 15,
			previousFootTreatmentOrDysfunction: 'None',
			otherDiabeticAssociatedComplications: 'Retinopathy',
			lastHbA1cReading: 7.5,
			lastHbA1cDate: new Date('2021-09-15').toISOString(),
			lastLipidProfile: 165,
			lastLipidProfileDate: new Date('2021-09-15').toISOString(),
			latestBp: 130,
			latestBpDate: new Date('2021-09-20').toISOString(),
			medications: true,
			medicationsInfo: 'Metformin, Statins',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '8',
		sequenceNumber: 8,
		firstName: 'Ethan',
		lastName: 'Adams',
		email: 'ethan.adams@example.com',
		address: {
			line1: '555 Willow Avenue',
			line2: 'Apt 9I',
			line3: '',
			county: 'Bristol',
			city: 'Bristol',
			postcode: 'BS1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1998-09-22').toISOString(),
		lastSeenDate: new Date('2021-09-25').toISOString(),
		gender: 'Male',
		height: 180,
		weight: 85,
		bmi: 26,
		phoneNumber: 7890123456,
		status: 'Flagged',
		treatmentStartDate: new Date('2021-10-01').toISOString(),
		nextVisitDate: new Date('2021-11-01').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE1',
			previousAmputation: false,
			yearsDiagnosedWithDiabetes: 2,
			previousFootTreatmentOrDysfunction: 'None',
			otherDiabeticAssociatedComplications: 'None',
			lastHbA1cReading: 6.8,
			lastHbA1cDate: new Date('2021-09-20').toISOString(),
			lastLipidProfile: 145,
			lastLipidProfileDate: new Date('2021-09-20').toISOString(),
			latestBp: 115,
			latestBpDate: new Date('2021-09-25').toISOString(),
			medications: true,
			medicationsInfo: 'Insulin',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '9',
		sequenceNumber: 9,
		firstName: 'Ava',
		lastName: 'Thomas',
		email: 'ava.thomas@example.com',
		address: {
			line1: '666 Oakwood Drive',
			line2: 'Apt 10J',
			line3: '',
			county: 'Leeds',
			city: 'Leeds',
			postcode: 'LS1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1987-06-14').toISOString(),
		lastSeenDate: new Date('2021-09-30').toISOString(),
		gender: 'Female',
		height: 165,
		weight: 70,
		bmi: 26,
		phoneNumber: 8901234567,
		status: 'New Patient',
		treatmentStartDate: new Date('2021-11-05').toISOString(),
		nextVisitDate: new Date('2021-12-05').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE2',
			previousAmputation: false,
			yearsDiagnosedWithDiabetes: 7,
			previousFootTreatmentOrDysfunction: 'None',
			otherDiabeticAssociatedComplications: 'None',
			lastHbA1cReading: 7.0,
			lastHbA1cDate: new Date('2021-09-25').toISOString(),
			lastLipidProfile: 155,
			lastLipidProfileDate: new Date('2021-09-25').toISOString(),
			latestBp: 120,
			latestBpDate: new Date('2021-09-30').toISOString(),
			medications: true,
			medicationsInfo: 'Metformin',
			otherDMorCVComplications: 'None',
		},
	},
	{
		id: '10',
		sequenceNumber: 10,
		firstName: 'Mia',
		lastName: 'Rodriguez',
		email: 'mia.rodriguez@example.com',
		address: {
			line1: '777 Pinecrest Lane',
			line2: 'Apt 11K',
			line3: '',
			county: 'Newcastle',
			city: 'Newcastle',
			postcode: 'NE1 1AA',
			country: 'United Kingdom',
		},
		birthDate: new Date('1975-01-08').toISOString(),
		lastSeenDate: new Date('2021-10-05').toISOString(),
		gender: 'Female',
		height: 160,
		weight: 65,
		bmi: 25,
		phoneNumber: 9012345678,
		status: 'New Patient',
		treatmentStartDate: new Date('2021-12-10').toISOString(),
		nextVisitDate: new Date('2022-01-10').toISOString(),
		diabetesDetails: {
			typeOfDiabetes: 'TYPE1',
			previousAmputation: true,
			yearsDiagnosedWithDiabetes: 20,
			previousFootTreatmentOrDysfunction: 'Amputation',
			otherDiabeticAssociatedComplications: 'Neuropathy',
			lastHbA1cReading: 8.2,
			lastHbA1cDate: new Date('2021-09-30').toISOString(),
			lastLipidProfile: 165,
			lastLipidProfileDate: new Date('2021-09-30').toISOString(),
			latestBp: 125,
			latestBpDate: new Date('2021-10-05').toISOString(),
			medications: true,
			medicationsInfo: 'Insulin, ACE inhibitors',
			otherDMorCVComplications: 'None',
		},
	},
];

export default patients;
