/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as ProtectedImport } from './../routes/_protected'
import { Route as AuthImport } from './../routes/_auth'
import { Route as SplatImport } from './../routes/$'
import { Route as IndexImport } from './../routes/index'
import { Route as ProtectedPatientsImport } from './../routes/_protected/patients'
import { Route as ProtectedMessagesImport } from './../routes/_protected/messages'
import { Route as AuthSignupImport } from './../routes/_auth/signup'
import { Route as AuthResetPasswordImport } from './../routes/_auth/reset-password'
import { Route as AuthLoginImport } from './../routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './../routes/_auth/forgot-password'
import { Route as AuthTEMPtoggletestImport } from './../routes/_auth/TEMP_toggle_test'
import { Route as ProtectedPatientsPatientIdImport } from './../routes/_protected/patients_.$patientId'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedPatientsRoute = ProtectedPatientsImport.update({
  path: '/patients',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedMessagesRoute = ProtectedMessagesImport.update({
  path: '/messages',
  getParentRoute: () => ProtectedRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTEMPtoggletestRoute = AuthTEMPtoggletestImport.update({
  path: '/TEMP_toggle_test',
  getParentRoute: () => AuthRoute,
} as any)

const ProtectedPatientsPatientIdRoute = ProtectedPatientsPatientIdImport.update(
  {
    path: '/patients/$patientId',
    getParentRoute: () => ProtectedRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/TEMP_toggle_test': {
      preLoaderRoute: typeof AuthTEMPtoggletestImport
      parentRoute: typeof AuthImport
    }
    '/_auth/forgot-password': {
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/reset-password': {
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_protected/messages': {
      preLoaderRoute: typeof ProtectedMessagesImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/patients': {
      preLoaderRoute: typeof ProtectedPatientsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/patients/$patientId': {
      preLoaderRoute: typeof ProtectedPatientsPatientIdImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SplatRoute,
  AuthRoute.addChildren([
    AuthTEMPtoggletestRoute,
    AuthForgotPasswordRoute,
    AuthLoginRoute,
    AuthResetPasswordRoute,
    AuthSignupRoute,
  ]),
  ProtectedRoute.addChildren([
    ProtectedMessagesRoute,
    ProtectedPatientsRoute,
    ProtectedPatientsPatientIdRoute,
  ]),
])

/* prettier-ignore-end */
